---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jdix-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sandbox.jdix.io
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sandbox.jdix.io
  resources:
  - sandboxes/finalizers
  verbs:
  - update
- apiGroups:
  - sandbox.jdix.io
  resources:
  - sandboxes/status
  - sandboxpools/status
  - sandboxtemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sandbox.jdix.io
  resources:
  - sandboxpools
  - sandboxtemplates
  verbs:
  - get
  - list
  - watch
